In [1]:
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
import re
import joblib

/Users/dipanshuparashar/Desktop/project_sync/Log_Classification_NLP_BERT_LLM/venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = pd.read_csv('../dataset/synthetic_logs.csv')
display(df)

,timestamp,source,log_message,target_label
0,6/27/25 7:20,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status
1,1/14/25 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error
2,1/17/25 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert
3,7/12/25 0:24,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status
4,6/2/25 18:25,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status
...,...,...,...,...
2405,8/13/25 7:29,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status
2406,1/11/25 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert
2407,8/3/25 3:07,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status
2408,11/11/25 11:52,BillingSystem,Email service affected by failed transmission,Critical Error
2409,12/25/25 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert

In [3]:
df.source.unique()

<StringArray>
[      'ModernCRM', 'AnalyticsEngine',        'ModernHR',   'BillingSystem',
   'ThirdPartyAPI',       'LegacyCRM']
Length: 6, dtype: str

In [4]:
df.target_label.unique()

<StringArray>
[        'HTTP Status',      'Critical Error',      'Security Alert',
               'Error', 'System Notification',      'Resource Usage',
         'User Action',      'Workflow Error', 'Deprecation Warning']
Length: 9, dtype: str

In [5]:
# encode log messages to vectors
model = SentenceTransformer('all-MiniLM-L6-v2')
texts = df['log_message'].astype(str).tolist()
embeddings = model.encode(texts)
embeddings[:2]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 11704.51it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

array([[-1.02939703e-01,  3.35459337e-02, -2.20260508e-02,
         1.55098503e-03, -9.86916851e-03, -1.78956285e-01,
        -6.34410381e-02, -6.01762049e-02,  2.81108320e-02,
         5.99620081e-02, -1.72618385e-02,  1.43374118e-03,
        -1.49560049e-01,  3.15288105e-03, -5.66030778e-02,
         2.71685906e-02, -1.49890184e-02, -3.54038104e-02,
        -3.62936780e-02, -1.45410160e-02, -5.61498804e-03,
         8.75538513e-02,  4.55120578e-02,  2.50964370e-02,
         1.00187566e-02,  1.24266557e-02, -1.39923617e-01,
         7.68695921e-02,  3.14095281e-02, -4.15253639e-03,
         4.36902307e-02,  1.71250347e-02, -8.00950974e-02,
         5.74006215e-02,  1.89091638e-02,  8.55261534e-02,
         3.96398902e-02, -1.34371802e-01, -1.44367898e-03,
         3.06708645e-03,  1.76854104e-01,  4.44882922e-03,
        -1.69274919e-02,  2.24266555e-02, -4.35050316e-02,
         6.09036861e-03, -9.98167414e-03, -6.23972639e-02,
         1.07371677e-02, -6.04894478e-03, -7.14660510e-02,
        -8.45803227e-03, -3.18019502e-02, -1.00518316e-01,
         2.25876574e-04, -1.89341512e-02, -3.17794420e-02,
         4.00861166e-02,  2.19177958e-02, -2.59527899e-02,
         5.84524758e-02, -8.12509209e-02,  2.12028679e-02,
        -5.02687469e-02,  1.32057359e-02,  1.32677599e-03,
         2.27063373e-02, -3.45793515e-02,  3.91547419e-02,
        -2.09433362e-02,  3.24824615e-03,  4.43961024e-02,
        -9.85357761e-02, -2.88894977e-02, -6.85029943e-03,
         5.38819507e-02,  6.46109730e-02, -2.45060623e-02,
         9.21828449e-02, -7.49869868e-02,  1.23995114e-02,
        -1.00026593e-01, -4.64910120e-02,  6.01570085e-02,
        -2.46480331e-02, -7.08075687e-02, -2.77270228e-02,
         9.72611234e-02,  3.85841466e-02, -1.44292954e-02,
        -7.46799924e-04, -1.04304692e-02, -1.61842518e-02,
         4.43628058e-02,  9.25997831e-03,  7.14166239e-02,
         6.37917742e-02,  4.94930707e-02, -6.02567606e-02,
         4.04806137e-02, -3.42860110e-02, -1.93880852e-02,
         6.61234185e-02,  6.01589046e-02,  1.09371161e-02,
        -5.38625475e-03,  1.44580239e-02,  9.25429910e-02,
        -3.14563476e-02, -1.84351522e-02,  9.91878565e-03,
        -1.85574945e-02,  1.31284085e-03,  2.26345583e-05,
         2.02729250e-03,  2.75255889e-02, -4.81927693e-02,
         5.42825386e-02, -7.32066780e-02,  4.88667339e-02,
         4.98490259e-02, -9.01137479e-03, -4.68906276e-02,
        -4.25886922e-02, -8.19524080e-02,  3.87106240e-02,
         7.85503238e-02,  1.46077096e-32,  1.66706704e-02,
         5.25494404e-02, -1.82450227e-02, -1.26686441e-02,
         6.52837157e-02, -2.11777836e-02, -4.06322256e-02,
         4.14948165e-02, -2.48361919e-02, -1.33068152e-02,
        -5.46753369e-02, -5.99133433e-04, -4.89247264e-03,
        -6.27359673e-02, -3.84878181e-02, -6.13543615e-02,
         8.27405527e-02,  2.34380476e-02, -8.63083825e-03,
         1.31002832e-02,  6.44214377e-02, -4.41361144e-02,
        -6.98634014e-02, -7.36060143e-02, -4.33264226e-02,
         6.96527259e-03, -5.05956449e-02, -1.60911772e-02,
        -5.66793606e-02,  3.35457292e-03,  5.34115992e-02,
         2.47761160e-02, -1.47986179e-02, -2.93242112e-02,
         7.30228573e-02, -1.86833534e-02,  8.13137069e-02,
        -2.69967783e-02, -5.68056256e-02, -6.59388602e-02,
        -5.95392939e-03,  2.85312980e-02, -7.85358697e-02,
        -2.76696403e-03, -3.26477597e-03, -9.28333029e-02,
        -7.27363378e-02, -3.31903771e-02,  1.01411082e-01,
         9.79881361e-02, -9.78740528e-02,  1.98667608e-02,
         2.38836650e-02, -1.81672685e-02, -3.73708680e-02,
         1.96558051e-03,  6.34425506e-02,  1.18270135e-02,
        -1.12041440e-02, -3.87316272e-02,  9.32424590e-02,
         4.26631700e-03, -1.66873075e-02, -6.87464774e-02,
         1.55118853e-02, -4.97755222e-02,  3.34492289e-02,
         8.00032169e-02,  2.12282054e-02,  1.34581864e-01,
        -2.30729729e-02,  5.53858280e-02,  3.07557788e-02,
        -2.93905698e-02,  2.31905207e-02, -9.34307054e-02,
         7.58034661e-02, -5.21206111e-03, -5.14522903e-02,
         3.32689285e-02,  3.67963612e-02, -1.06451046e-02,
         1.01635391e-02, -2.07650755e-02, -5.85519597e-02,
         4.79328893e-02,  2.13694256e-02,  8.76213163e-02,
         3.35487979e-03, -3.80336270e-02, -1.81205757e-02,
         6.87440438e-03,  5.15879728e-02, -4.75598350e-02,
        -6.12065159e-02, -1.45483633e-32,  4.12798952e-03,
         4.59644198e-03, -5.63901253e-02,  4.32476215e-03,
        -1.09445094e-03,  9.31958109e-03, -2.20268369e-02,
         5.79564832e-02, -1.44787543e-02,  4.64156307e-02,
         1.43542811e-01, -6.89756051e-02,  6.09631576e-02,
        -8.93743709e-02,  2.40918789e-02,  2.06010025e-02,
        -2.82415729e-02, -6.48316219e-02,  5.64794801e-02,
        -7.48328399e-03, -3.52058560e-02,  8.51060450e-02,
         1.30359400e-02,  2.02258378e-02, -1.44390520e-02,
        -4.63718139e-02,  1.77210197e-02,  1.59105267e-02,
        -9.51008871e-02, -3.54527906e-02,  2.08695717e-02,
         3.84377409e-03, -8.77918229e-02,  6.44574985e-02,
         1.44170625e-02,  3.84731242e-03,  4.70991507e-02,
         4.94661964e-02,  1.53861931e-02, -2.59578712e-02,
         9.10895243e-02,  1.83307845e-02, -5.89206666e-02,
         2.51992941e-02, -3.30373868e-02,  8.23344737e-02,
         1.74791589e-02,  6.48047924e-02, -1.19673712e-02,
        -3.31778415e-02,  3.00177075e-02,  3.54220755e-02,
        -1.39624169e-02,  6.69272766e-02,  3.87919247e-02,
         6.06916994e-02,  1.17963005e-03, -2.38786172e-02,
        -1.26930520e-01,  1.13847116e-02,  1.59289837e-02,
        -1.29426736e-02, -8.63248035e-02,  8.53664335e-03,
         6.03761002e-02,  1.51122045e-02, -1.19132407e-01,
         1.15234368e-02,  5.97089678e-02, -3.93346250e-02,
         1.55674433e-02,  1.04602398e-02, -4.72457185e-02,
        -2.59243902e-02,  9.98528581e-03,  3.07145957e-02,
        -7.14843944e-02,  6.98958989e-03, -1.55133251e-02,
         2.18864642e-02, -2.78145857e-02,  6.92733750e-02,
        -2.75903996e-02,  2.62429789e-02,  3.52562815e-02,
        -4.26419191e-02,  7.46296311e-04,  6.59866631e-02,
        -5.15105166e-02, -3.58433761e-02, -6.53443020e-03,
        -2.75858454e-02, -1.00125633e-01,  7.83325955e-02,
        -1.45799210e-02, -6.18457392e-08,  2.00325772e-02,
         6.59785420e-02, -2.04702541e-02,  1.64044239e-02,
         7.63001144e-02,  7.32182339e-02,  5.65787312e-03,
        -6.97702519e-04, -3.63798556e-03,  6.02394752e-02,
        -3.27187479e-02, -6.45837858e-02, -5.97953387e-02,
        -1.76695734e-02,  6.10145694e-03, -5.63489785e-03,
        -1.22972213e-01,  6.35818318e-02, -2.19432414e-02,
        -1.16406582e-01,  2.34365035e-02, -7.23525137e-02,
         2.31774561e-02, -6.55987486e-02, -7.42682442e-02,
         2.60145757e-02,  3.59757915e-02,  7.68432915e-02,
        -3.08057256e-02, -2.34793574e-02, -6.30426630e-02,
        -3.62157561e-02, -1.03560304e-02, -4.75603119e-02,
        -2.87521482e-02,  2.96401139e-02, -5.26899705e-03,
         5.67889512e-02, -3.74486158e-03,  3.09612248e-02,
         3.48227508e-02,  3.78607623e-02,  2.10155714e-02,
         2.70691738e-02,  5.25521077e-02,  7.16229081e-02,
        -5.53754903e-03,  4.01093848e-02,  5.16276658e-02,
        -2.67314650e-02,  5.94224446e-02, -4.29224409e-02,
        -1.19761070e-02,  3.05986255e-02, -7.40331560e-02,
         1.84221584e-02, -8.64860322e-03, -8.83558616e-02,
        -5.91984242e-02, -1.00898906e-04,  1.12913668e-01,
         4.57784394e-03, -4.25971784e-02,  3.22623155e-03],
       [ 8.04573391e-03, -3.57392617e-02,  4.93873395e-02,
        -7.19200540e-03,  6.17594225e-04, -9.05684754e-02,
         5.75595237e-02, -4.39445451e-02,  1.74751058e-02,
         5.21203056e-02, -4.62332591e-02,  2.49039251e-02,
         4.80811261e-02,  6.86636344e-02,  3.56147550e-02,
         3.00088692e-02,  2.61450615e-02, -9.05242786e-02,
        -8.02173465e-02,  5.04851453e-02, -7.90870413e-02,
        -1.76850613e-03, -2.48927213e-02,  9.02153179e-02,
         5.83691010e-03, -6.91071302e-02, -6.67965412e-02,
        -6.99115871e-03, -1.04566067e-01, -2.66474020e-02,
         3.05640660e-02,  2.02934332e-02,  2.25454140e-02,
        -4.22680983e-03,  1.11173084e-02,  6.78260401e-02,
         1.06072798e-02,  7.56636113e-02, -8.22777972e-02,
         8.45727697e-03, -6.97611719e-02, -4.21974622e-02,
        -1.05675403e-02,  2.23673210e-02,  5.64497039e-02,
         8.16499349e-03,  1.09344065e-01,  3.16565037e-02,
        -1.76923983e-02, -3.21071222e-02, -3.39976065e-02,
        -4.91865270e-04,  3.72882909e-03,  2.83771995e-02,
        -1.28521733e-02, -1.07931101e-03, -6.32418767e-02,
         6.89901337e-02,  1.77270249e-02, -5.20959273e-02,
         8.28308053e-03,  5.45032136e-02, -5.42099178e-02,
        -4.53332700e-02, -4.07493711e-02, -2.82698255e-02,
         1.23605467e-02, -2.13815887e-02, -2.36266199e-02,
         1.25317844e-02, -2.37170663e-02,  3.97411585e-02,
        -1.24362171e-01,  7.60625675e-02,  5.50833121e-02,
         8.28216895e-02,  2.97119413e-02, -1.84067301e-02,
        -1.96194537e-02,  5.54319024e-02, -3.49143632e-02,
        -4.14677151e-02, -3.37047316e-02,  7.31324553e-02,
         4.41837087e-02,  2.55246125e-02, -8.26404244e-03,
        -1.07323499e-02, -4.26244214e-02, -2.84962379e-03,
         7.38559067e-02,  2.27768477e-02,  7.15384434e-04,
         4.36012223e-02,  5.09080216e-02,  6.38482794e-02,
        -2.73155794e-02, -6.55021593e-02, -7.69265592e-02,
         3.55171375e-02,  9.60494280e-02,  2.18195822e-02,
         1.20155150e-02, -1.17864003e-02, -4.57934802e-03,
        -8.58034287e-03,  3.37150097e-02,  2.31918972e-02,
        -7.58325458e-02, -5.23878746e-02,  4.53933813e-02,
        -3.80786061e-02, -3.34904715e-02,  9.20353234e-02,
         2.87689138e-02, -3.33817266e-02, -1.95853226e-03,
        -3.04530811e-04, -1.70499142e-02,  2.85335910e-02,
        -8.81095454e-02, -4.02252674e-02, -4.00093682e-02,
        -1.03193102e-02, -2.51968428e-02,  2.14092582e-02,
         1.31045297e-01, -5.29633765e-34, -1.09651715e-01,
         1.29811466e-02,  5.92657551e-03,  4.73506488e-02,
        -8.60292558e-03, -3.67089920e-02,  3.05214841e-02,
         5.53067103e-02, -4.71985415e-02, -1.25118876e-02,
        -1.15366466e-01,  9.08006541e-03,  1.07346520e-01,
        -4.94735315e-02, -1.34290727e-02, -4.61562537e-02,
         2.45320462e-02,  9.45082400e-03,  2.04324387e-02,
        -3.99918184e-02, -4.67826389e-02,  2.21171584e-02,
        -4.58187312e-02, -8.13272409e-03, -7.65669812e-03,
         1.92283783e-02,  4.85844538e-02, -2.55902205e-02,
         1.61550229e-03, -1.37180462e-02,  9.67310090e-03,
         7.36411475e-03,  1.14088068e-02,  1.28853470e-01,
         7.71843316e-03,  7.06362203e-02,  2.54451539e-02,
         4.06523868e-02,  2.44038943e-02,  1.43776415e-02,
        -6.00932315e-02,  7.38180652e-02, -2.44701710e-02,
         8.98901671e-02,  3.17052449e-03,  1.01834476e-01,
         4.17741574e-02, -5.95178157e-02, -3.23181450e-02,
         3.80939171e-02,  1.21155838e-02, -4.07834314e-02,
         2.84823179e-02,  4.90988493e-02, -9.35697928e-03,
         6.50074482e-02,  7.23532289e-02, -1.67793036e-02,
        -8.22415575e-03, -1.61573030e-02,  5.96225299e-02,
        -3.36084552e-02,  2.12108232e-02, -6.06090799e-02,
         1.54377624e-01, -7.24146813e-02, -3.77272032e-02,
        -3.26889642e-02, -1.80382060e-03, -1.01960041e-02,
        -1.60677545e-03, -6.91846088e-02,  8.28444511e-02,
         9.88840312e-02,  3.45473574e-03, -9.90247130e-02,
        -3.52827162e-02, -7.13178739e-02, -4.96000946e-02,
        -3.43955085e-02, -8.13041851e-02,  4.81447391e-02,
         5.00679435e-03, -2.21499521e-02, -5.60056865e-02,
         1.00068096e-02, -3.59793454e-02,  1.06184319e-01,
        -4.54196408e-02,  7.16393292e-02, -2.36773510e-02,
         9.98145342e-03,  2.73602046e-02,  1.05985492e-01,
         4.60164249e-02,  9.59029454e-34, -1.12306990e-01,
         2.78911889e-02, -3.35900933e-02,  5.39242700e-02,
        -2.22291313e-02,  1.53769068e-02,  3.10411751e-02,
         3.39010954e-02,  7.43166730e-02,  3.42471153e-02,
        -3.35056870e-03, -2.05350984e-02, -3.62369791e-02,
         2.29334272e-02, -3.01991608e-02, -1.00819945e-01,
         3.29193920e-02,  6.77542612e-02,  1.35644544e-02,
        -5.20550227e-03, -6.58159032e-02,  9.54550803e-02,
        -1.34038934e-02,  1.53885018e-02, -7.22936466e-02,
         9.67836082e-02, -8.08119699e-02, -4.53454675e-03,
        -6.42011315e-02, -4.99278791e-02,  4.64197397e-02,
         2.21340004e-02,  3.13109383e-02,  9.13568512e-02,
        -4.61120494e-02, -1.02761038e-01,  3.04415729e-02,
         5.09875491e-02,  6.70140684e-02,  1.04042431e-02,
         1.63534079e-02,  3.92030627e-02,  2.17153635e-02,
         5.36603332e-02,  3.62809487e-02, -4.22140770e-02,
        -2.47226693e-02,  1.90311708e-02,  3.61724161e-02,
         6.37021735e-02, -3.21582262e-03, -8.50392878e-03,
         3.94655801e-02,  9.02654324e-03,  1.93095654e-02,
         6.60718232e-02,  1.02694873e-02, -4.43854295e-02,
        -1.56523138e-02, -1.55714341e-02,  1.32904621e-02,
        -1.16108647e-02,  4.21831720e-02, -5.44776618e-02,
         1.29237190e-01, -2.25757398e-02,  5.26203550e-02,
        -1.58437118e-02,  9.33164656e-02,  6.38019480e-03,
        -9.36159026e-03, -6.08875342e-02, -3.27308141e-02,
        -3.44816409e-02,  3.29973958e-02, -4.79391888e-02,
        -9.81300771e-02,  2.91164853e-02, -2.70903464e-02,
         1.81866940e-02, -1.73859913e-02, -4.40371186e-02,
        -7.97002465e-02,  3.01646441e-02, -6.35260791e-02,
         1.25962850e-02,  8.50250125e-02, -4.58911099e-02,
         5.81017099e-02, -2.71002855e-02,  8.42775479e-02,
        -4.09972779e-02, -3.37656885e-02,  1.02088815e-02,
        -2.54192557e-02, -1.40610315e-08,  4.94446754e-02,
        -9.04356092e-02, -6.06709905e-02,  8.29530060e-02,
        -3.29032876e-02,  4.14910726e-02,  9.99592431e-03,
         6.96136849e-03,  3.99236800e-03, -3.24333273e-02,
        -3.14657055e-02, -5.33161797e-02, -3.80913094e-02,
         1.62076857e-02,  2.45778989e-02, -7.26419166e-02,
        -6.56893775e-02, -8.23131874e-02, -8.00500810e-02,
        -5.36648929e-02,  5.60894497e-02, -1.10912947e-02,
         9.62166581e-04, -1.22690335e-01, -5.13837114e-02,
         9.96703841e-03,  1.00696050e-02,  1.07073061e-01,
         1.19757699e-02,  1.00423172e-02, -6.28261939e-02,
        -7.49697015e-02, -6.34070160e-03, -2.72201132e-02,
        -1.28096163e-01, -2.62459815e-02, -1.81465298e-02,
        -9.85359699e-02, -3.02990265e-02, -4.02614735e-02,
         9.94290635e-02,  5.35999909e-02,  2.74899639e-02,
        -5.53680072e-03,  8.43570977e-02,  8.35161731e-02,
         3.74304205e-02,  7.11937770e-02,  2.98903026e-02,
         2.32728701e-02, -3.62112634e-02,  6.20540008e-02,
         2.15148628e-02,  5.19732311e-02,  1.45338271e-02,
        -4.60966676e-02,  5.02554402e-02, -7.27027357e-02,
         2.92778611e-02,  5.62662818e-02, -3.86355035e-02,
         1.53832138e-02, -6.23094402e-02, -2.77466550e-02]], dtype=float32)

In [6]:
# DBSCAN clustering
dbscan = DBSCAN(eps=0.2, min_samples=1, metric='cosine')
clusters = dbscan.fit_predict(embeddings)
df['cluster'] = clusters
df.head()

,timestamp,source,log_message,target_label,cluster
0,6/27/25 7:20,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,0
1,1/14/25 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,1
2,1/17/25 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,2
3,7/12/25 0:24,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,0
4,6/2/25 18:25,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,0

In [7]:
df[df.cluster == 1][['log_message', 'target_label']].head(20)

                                            log_message    target_label
1        Email service experiencing issues with sending  Critical Error
10             Email server encountered a sending fault           Error
217          Mail service encountered a delivery glitch           Error
248    Service disruption caused by email sending error  Critical Error
265           Email system had a problem sending emails           Error
361           Email service experienced a sending issue           Error
450          Email delivery system encountered an error           Error
477      Email transmission error caused service impact  Critical Error
570           Email service impacted by sending failure  Critical Error
678              Email delivery problem affected system  Critical Error
695        Service outage due to email delivery problem  Critical Error
816            Error in email delivery affected service  Critical Error
926           Email service suffered a delivery failure           Error
1011            Error in email sending impacted service  Critical Error
1018           Mail service impacted by delivery glitch  Critical Error
1046  Email service had a difficulty delivering mess...           Error
1058              Email system failed to deliver emails           Error
1082           Delivery failure impacted email services  Critical Error
1151             Mail service was unable to send emails           Error
1176          Email provider faced a delivery challenge           Error

In [8]:
cluster_counts = df['cluster'].value_counts().sort_values(ascending=False)
print(cluster_counts)

for cluster_id, count in cluster_counts.items():
    if count > 10:
        print(f"\nCluster {cluster_id} (count {count})")
        for msg in df.loc[df['cluster'] == cluster_id, 'log_message'].head(5).tolist():
            print("-", msg)

cluster
0      1017
5       147
11      100
13       86
7        60
       ...
99        1
100       1
102       1
103       1
135       1
Name: count, Length: 136, dtype: int64

Cluster 0 (count 1017)
- nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118
- nova.osapi_compute.wsgi.server [req-4895c258-b2f8-488f-a2a3-4fae63982e48 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" HTTP status code -  200 len: 211 time: 0.0968180
- nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.2280791
- nova.osapi_compute.wsgi.server [req-f0bffbc3-5ab0-4916-91c1-0a61dd7d4ec2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" Return code: 200 len: 1874 time: 0.2131531
- nova.osapi_compute.wsgi.server [req-2bf7cfee-a236-42f3-8fb1-96fefab0b302 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.1794369

Cluster 5 (count 147)
- nova.compute.claims [req-a07ac654-8e81-416d-bfbb-189116b07969 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: bf8c824d-f099-4433-a41e-e3da7578262e] Total memory: 64172 MB, used: 512.00 MB
- nova.compute.claims [req-d6986b54-3735-4a42-9074-0ba7d9717de9 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: af5f7392-f7d4-4298-b647-c98924c64aa1] memory limit: 96258.00 MB, free: 95746.00 MB
- nova.compute.claims [req-72b4858f-049e-49e1-b31e-b562c5018eaf 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 63a0d960-70b6-44c6-b606-491478a5cadf] disk limit not specified, defaulting to unlimited
- nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a5-7861d247cafa 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: d96a117b-0193-4549-bdcc-63b917273d1d] vcpu limit not specified, defaulting to unlimited
- nova.compute.claims [req-d38f479d-9bb9-4276-9688-52607e8fd350 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 95960536-049b-41f6-9049-05fc479b6a7c] disk limit not specified, defaulting to unlimited

Cluster 11 (count 100)
- User User685 logged out.
- User User395 logged in.
- User User225 logged in.
- User User494 logged out.
- User User900 logged in.

Cluster 13 (count 86)
- Backup started at 2025-05-14 07:06:55.
- Backup started at 2025-02-15 20:00:19.
- Backup ended at 2025-08-08 13:06:23.
- Backup started at 2025-11-14 08:27:43.
- Backup started at 2025-12-09 10:19:11.

Cluster 7 (count 60)
- Multiple bad login attempts detected on user 8538 account
- Multiple login failures occurred on user 9052 account
- User 7153 made multiple incorrect login attempts
- User 8300 made multiple incorrect login attempts
- Multiple login failures were detected for user 6373

Cluster 8 (count 60)
- Backup completed successfully.
- Backup completed successfully.
- Backup completed successfully.
- Backup completed successfully.
- Backup completed successfully.

Cluster 21 (count 58)
- System updated to version 3.9.1.
- System updated to version 5.5.4.
- System updated to version 4.7.4.
- System updated to version 3.7.7.
- System updated to version 2.6.2.

Cluster 3 (count 57)
- Shard 6 replication task ended in failure
- Data replication task for shard 14 did not complete
- Data replication task failed for shard 17
- Replication of data to shard 14 failed
- Data replication task for shard 6 did not complete

Cluster 4 (count 53)
- File data_6169.csv uploaded successfully by user User953.
- File data_3847.csv uploaded successfully by user User175.
- File data_7366.csv uploaded successfully by user User282.
- File data_1206.csv uploaded successfully by user User359.
- File data_1503.csv uploaded successfully by user User151.

Cluster 17 (count 52)
- Denied access attempt on restricted account Account2682
- Unauthorized login attempt on protected account Account5030
- Account Account9437 blocked due to failed login
- Account Account7999 access denied due to login failure
- Invalid login attempt made on secured account Account7864

Cluster 6 (count 51)
- Critical system unit error: unit ID Component55
- System component malfunction: component ID Component79
- Critical system element is down: element ID Component96
- Essential system part malfunction: part ID Component6
- Failure occurred in critical system component: component ID Component92

Cluster 32 (count 51)
- Disk cleanup completed successfully.
- Disk cleanup completed successfully.
- Disk cleanup completed successfully.
- Disk cleanup completed successfully.
- Disk cleanup completed successfully.

Cluster 16 (count 48)
- System reboot initiated by user User243.
- System reboot initiated by user User471.
- System reboot initiated by user User216.
- System reboot initiated by user User639.
- System reboot initiated by user User819.

Cluster 20 (count 48)
- User 7662 tried to bypass API security measures
- User 2367 failed to provide valid API access credentials
- User 3569 made an unauthorized API request
- Unauthorized user 2968 tried to access restricted API
- User 2186 attempted to access API without proper authorization

Cluster 9 (count 44)
- Account with ID 5351 created by User634.
- Account with ID 7813 created by User373.
- Account with ID 9827 created by User965.
- Account with ID 2520 created by User546.
- Account with ID 2300 created by User964.

Cluster 1 (count 39)
- Email service experiencing issues with sending
- Email server encountered a sending fault
- Mail service encountered a delivery glitch
- Service disruption caused by email sending error
- Email system had a problem sending emails

Cluster 10 (count 30)
- nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=512MB phys_disk=15GB used_disk=0GB total_vcpus=16 used_vcpus=0 pci_stats=[]
- nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
- nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 0
- nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
- nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]

Cluster 34 (count 25)
- Abnormal behavior found on server 10, possible security threat
- Security alert: suspicious activity on server 1
- Anomalous activity identified on server 23, security review recommended
- Server 27 experienced potential security incident, review required
- Server 36 experienced potential security incident, review required

Cluster 14 (count 20)
- Detection of multiple disk faults in RAID setup
- RAID array suffered multiple hard drive failures
- RAID array experienced multiple disk crashes
- Multiple hard drive issues in RAID configuration found
- Identification of multiple faulty disks in RAID array

Cluster 52 (count 20)
- Service health check was not successful because of SSL certificate validation failures.
- Invalid SSL certificate resulted in a failed service health check.
- Service health check failure was due to an invalid or improperly configured SSL certificate.
- An issue with the SSL certificate caused the service health check to fail.
- Service health check failure was caused by an expired SSL certificate.

Cluster 53 (count 20)
- Module X experienced an invalid data format issue
- Input format mismatch occurred in module X
- Module X reported an error in input format validation
- Module X failed to process input due to formatting error
- Input data format in module X was invalid or corrupted

Cluster 18 (count 17)
- Boot process terminated unexpectedly due to kernel issue
- System encountered kernel panic during initialization phase
- Boot process was stopped by kernel malfunction
- System encountered kernel failure during bootup sequence
- Boot sequence failed due to kernel panic

Cluster 25 (count 13)
- System configuration is no longer valid
- Configuration is corrupted throughout the system
- Cross-system configuration failure occurred
- System configuration is experiencing errors
- Configuration malfunction is system-wide

Cluster 42 (count 13)
- User 5127 has escalated admin privileges without authorization
- User 9745 has escalated to admin level
- User 8483 escalated privileges to admin level
- User 1987 has escalated to admin level
- User 8395 escalated privileges to admin level

Cluster 59 (count 12)
- Potential security threat: Admin privilege escalation for user 5130
- Admin privilege escalation alert for user 2893
- Admin privilege escalation alert for user 8532
- Potential security threat: Admin privilege escalation for user 1554
- Warning: Potential admin privilege escalation for user 5720

Cluster 26 (count 11)
- Privilege elevation detected for user 5038
- Elevation of admin privileges detected for user 6137
- Elevation of admin privileges detected for user 4907
- User 6069 has been granted elevated admin privileges
- Admin privilege elevation warning for user 7574

In [10]:
def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (in|out).": "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.match(pattern, log_message, re.IGNORECASE):
            return label
    return None

In [12]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)
df[df.regex_label.notnull()]

,timestamp,source,log_message,target_label,cluster,regex_label
7,10/11/25 8:44,ModernHR,File data_6169.csv uploaded successfully by us...,System Notification,4,System Notification
14,1/4/25 1:43,ThirdPartyAPI,File data_3847.csv uploaded successfully by us...,System Notification,4,System Notification
15,5/1/25 9:41,ModernCRM,Backup completed successfully.,System Notification,8,System Notification
18,2/22/25 17:49,ModernCRM,Account with ID 5351 created by User634.,User Action,9,User Action
27,9/24/25 19:57,ThirdPartyAPI,User User685 logged out.,User Action,11,User Action
...,...,...,...,...,...,...
2376,6/27/25 8:47,ModernCRM,System updated to version 2.0.5.,System Notification,21,System Notification
2381,9/5/25 6:39,ThirdPartyAPI,Disk cleanup completed successfully.,System Notification,32,System Notification
2394,4/3/25 13:13,ModernHR,Disk cleanup completed successfully.,System Notification,32,System Notification
2395,5/2/25 14:29,ThirdPartyAPI,Backup ended at 2025-05-06 11:23:16.,System Notification,13,System Notification
2403,10/1/25 1:31,ModernCRM,Backup completed successfully.,System Notification,8,System Notification

In [13]:
df_non_regex = df[df['regex_label'].isnull()].copy()
df_non_regex.shape

(1910, 6)

In [14]:
small_labels = df_non_regex['target_label'].value_counts()
small_labels = small_labels[small_labels <= 5]

print("target_labels with 5 or fewer rows:")
print(small_labels)

# Optional: show rows for those labels
print("\nRows for those target_labels:")
print(df_non_regex[df_non_regex['target_label'].isin(small_labels.index)][['target_label', 'log_message']])

target_labels with 5 or fewer rows:
target_label
Workflow Error         4
Deprecation Warning    3
Name: count, dtype: int64

Rows for those target_labels:
             target_label                                        log_message
60         Workflow Error  Lead conversion failed for prospect ID 7842 du...
255   Deprecation Warning  API endpoint 'getCustomerDetails' is deprecate...
377        Workflow Error  Customer follow-up process for lead ID 5621 fa...
1325       Workflow Error  Escalation rule execution failed for ticket ID...
1734  Deprecation Warning  The 'ExportToCSV' feature is outdated. Please ...
1826  Deprecation Warning  Support for legacy authentication methods will...
2217       Workflow Error  Task assignment for TeamID 3425 could not comp...

In [15]:
df_non_legacy=df_non_regex[df_non_regex.source!='LegacyCRM']
df_non_legacy.source.unique()

<StringArray>
['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem', 'ThirdPartyAPI']
Length: 5, dtype: str

In [16]:
texts_non_legacy = df_non_legacy['log_message'].astype(str).tolist()
filtered_embeddings = model.encode(texts_non_legacy)
filtered_embeddings[:2]

array([[-1.02939703e-01,  3.35459337e-02, -2.20260508e-02,
         1.55098503e-03, -9.86916851e-03, -1.78956285e-01,
        -6.34410381e-02, -6.01762049e-02,  2.81108320e-02,
         5.99620081e-02, -1.72618385e-02,  1.43374118e-03,
        -1.49560049e-01,  3.15288105e-03, -5.66030778e-02,
         2.71685906e-02, -1.49890184e-02, -3.54038104e-02,
        -3.62936780e-02, -1.45410160e-02, -5.61498804e-03,
         8.75538513e-02,  4.55120578e-02,  2.50964370e-02,
         1.00187566e-02,  1.24266557e-02, -1.39923617e-01,
         7.68695921e-02,  3.14095281e-02, -4.15253639e-03,
         4.36902307e-02,  1.71250347e-02, -8.00950974e-02,
         5.74006215e-02,  1.89091638e-02,  8.55261534e-02,
         3.96398902e-02, -1.34371802e-01, -1.44367898e-03,
         3.06708645e-03,  1.76854104e-01,  4.44882922e-03,
        -1.69274919e-02,  2.24266555e-02, -4.35050316e-02,
         6.09036861e-03, -9.98167414e-03, -6.23972639e-02,
         1.07371677e-02, -6.04894478e-03, -7.14660510e-02,
        -8.45803227e-03, -3.18019502e-02, -1.00518316e-01,
         2.25876574e-04, -1.89341512e-02, -3.17794420e-02,
         4.00861166e-02,  2.19177958e-02, -2.59527899e-02,
         5.84524758e-02, -8.12509209e-02,  2.12028679e-02,
        -5.02687469e-02,  1.32057359e-02,  1.32677599e-03,
         2.27063373e-02, -3.45793515e-02,  3.91547419e-02,
        -2.09433362e-02,  3.24824615e-03,  4.43961024e-02,
        -9.85357761e-02, -2.88894977e-02, -6.85029943e-03,
         5.38819507e-02,  6.46109730e-02, -2.45060623e-02,
         9.21828449e-02, -7.49869868e-02,  1.23995114e-02,
        -1.00026593e-01, -4.64910120e-02,  6.01570085e-02,
        -2.46480331e-02, -7.08075687e-02, -2.77270228e-02,
         9.72611234e-02,  3.85841466e-02, -1.44292954e-02,
        -7.46799924e-04, -1.04304692e-02, -1.61842518e-02,
         4.43628058e-02,  9.25997831e-03,  7.14166239e-02,
         6.37917742e-02,  4.94930707e-02, -6.02567606e-02,
         4.04806137e-02, -3.42860110e-02, -1.93880852e-02,
         6.61234185e-02,  6.01589046e-02,  1.09371161e-02,
        -5.38625475e-03,  1.44580239e-02,  9.25429910e-02,
        -3.14563476e-02, -1.84351522e-02,  9.91878565e-03,
        -1.85574945e-02,  1.31284085e-03,  2.26345583e-05,
         2.02729250e-03,  2.75255889e-02, -4.81927693e-02,
         5.42825386e-02, -7.32066780e-02,  4.88667339e-02,
         4.98490259e-02, -9.01137479e-03, -4.68906276e-02,
        -4.25886922e-02, -8.19524080e-02,  3.87106240e-02,
         7.85503238e-02,  1.46077096e-32,  1.66706704e-02,
         5.25494404e-02, -1.82450227e-02, -1.26686441e-02,
         6.52837157e-02, -2.11777836e-02, -4.06322256e-02,
         4.14948165e-02, -2.48361919e-02, -1.33068152e-02,
        -5.46753369e-02, -5.99133433e-04, -4.89247264e-03,
        -6.27359673e-02, -3.84878181e-02, -6.13543615e-02,
         8.27405527e-02,  2.34380476e-02, -8.63083825e-03,
         1.31002832e-02,  6.44214377e-02, -4.41361144e-02,
        -6.98634014e-02, -7.36060143e-02, -4.33264226e-02,
         6.96527259e-03, -5.05956449e-02, -1.60911772e-02,
        -5.66793606e-02,  3.35457292e-03,  5.34115992e-02,
         2.47761160e-02, -1.47986179e-02, -2.93242112e-02,
         7.30228573e-02, -1.86833534e-02,  8.13137069e-02,
        -2.69967783e-02, -5.68056256e-02, -6.59388602e-02,
        -5.95392939e-03,  2.85312980e-02, -7.85358697e-02,
        -2.76696403e-03, -3.26477597e-03, -9.28333029e-02,
        -7.27363378e-02, -3.31903771e-02,  1.01411082e-01,
         9.79881361e-02, -9.78740528e-02,  1.98667608e-02,
         2.38836650e-02, -1.81672685e-02, -3.73708680e-02,
         1.96558051e-03,  6.34425506e-02,  1.18270135e-02,
        -1.12041440e-02, -3.87316272e-02,  9.32424590e-02,
         4.26631700e-03, -1.66873075e-02, -6.87464774e-02,
         1.55118853e-02, -4.97755222e-02,  3.34492289e-02,
         8.00032169e-02,  2.12282054e-02,  1.34581864e-01,
        -2.30729729e-02,  5.53858280e-02,  3.07557788e-02,
        -2.93905698e-02,  2.31905207e-02, -9.34307054e-02,
         7.58034661e-02, -5.21206111e-03, -5.14522903e-02,
         3.32689285e-02,  3.67963612e-02, -1.06451046e-02,
         1.01635391e-02, -2.07650755e-02, -5.85519597e-02,
         4.79328893e-02,  2.13694256e-02,  8.76213163e-02,
         3.35487979e-03, -3.80336270e-02, -1.81205757e-02,
         6.87440438e-03,  5.15879728e-02, -4.75598350e-02,
        -6.12065159e-02, -1.45483633e-32,  4.12798952e-03,
         4.59644198e-03, -5.63901253e-02,  4.32476215e-03,
        -1.09445094e-03,  9.31958109e-03, -2.20268369e-02,
         5.79564832e-02, -1.44787543e-02,  4.64156307e-02,
         1.43542811e-01, -6.89756051e-02,  6.09631576e-02,
        -8.93743709e-02,  2.40918789e-02,  2.06010025e-02,
        -2.82415729e-02, -6.48316219e-02,  5.64794801e-02,
        -7.48328399e-03, -3.52058560e-02,  8.51060450e-02,
         1.30359400e-02,  2.02258378e-02, -1.44390520e-02,
        -4.63718139e-02,  1.77210197e-02,  1.59105267e-02,
        -9.51008871e-02, -3.54527906e-02,  2.08695717e-02,
         3.84377409e-03, -8.77918229e-02,  6.44574985e-02,
         1.44170625e-02,  3.84731242e-03,  4.70991507e-02,
         4.94661964e-02,  1.53861931e-02, -2.59578712e-02,
         9.10895243e-02,  1.83307845e-02, -5.89206666e-02,
         2.51992941e-02, -3.30373868e-02,  8.23344737e-02,
         1.74791589e-02,  6.48047924e-02, -1.19673712e-02,
        -3.31778415e-02,  3.00177075e-02,  3.54220755e-02,
        -1.39624169e-02,  6.69272766e-02,  3.87919247e-02,
         6.06916994e-02,  1.17963005e-03, -2.38786172e-02,
        -1.26930520e-01,  1.13847116e-02,  1.59289837e-02,
        -1.29426736e-02, -8.63248035e-02,  8.53664335e-03,
         6.03761002e-02,  1.51122045e-02, -1.19132407e-01,
         1.15234368e-02,  5.97089678e-02, -3.93346250e-02,
         1.55674433e-02,  1.04602398e-02, -4.72457185e-02,
        -2.59243902e-02,  9.98528581e-03,  3.07145957e-02,
        -7.14843944e-02,  6.98958989e-03, -1.55133251e-02,
         2.18864642e-02, -2.78145857e-02,  6.92733750e-02,
        -2.75903996e-02,  2.62429789e-02,  3.52562815e-02,
        -4.26419191e-02,  7.46296311e-04,  6.59866631e-02,
        -5.15105166e-02, -3.58433761e-02, -6.53443020e-03,
        -2.75858454e-02, -1.00125633e-01,  7.83325955e-02,
        -1.45799210e-02, -6.18457392e-08,  2.00325772e-02,
         6.59785420e-02, -2.04702541e-02,  1.64044239e-02,
         7.63001144e-02,  7.32182339e-02,  5.65787312e-03,
        -6.97702519e-04, -3.63798556e-03,  6.02394752e-02,
        -3.27187479e-02, -6.45837858e-02, -5.97953387e-02,
        -1.76695734e-02,  6.10145694e-03, -5.63489785e-03,
        -1.22972213e-01,  6.35818318e-02, -2.19432414e-02,
        -1.16406582e-01,  2.34365035e-02, -7.23525137e-02,
         2.31774561e-02, -6.55987486e-02, -7.42682442e-02,
         2.60145757e-02,  3.59757915e-02,  7.68432915e-02,
        -3.08057256e-02, -2.34793574e-02, -6.30426630e-02,
        -3.62157561e-02, -1.03560304e-02, -4.75603119e-02,
        -2.87521482e-02,  2.96401139e-02, -5.26899705e-03,
         5.67889512e-02, -3.74486158e-03,  3.09612248e-02,
         3.48227508e-02,  3.78607623e-02,  2.10155714e-02,
         2.70691738e-02,  5.25521077e-02,  7.16229081e-02,
        -5.53754903e-03,  4.01093848e-02,  5.16276658e-02,
        -2.67314650e-02,  5.94224446e-02, -4.29224409e-02,
        -1.19761070e-02,  3.05986255e-02, -7.40331560e-02,
         1.84221584e-02, -8.64860322e-03, -8.83558616e-02,
        -5.91984242e-02, -1.00898906e-04,  1.12913668e-01,
         4.57784394e-03, -4.25971784e-02,  3.22623155e-03],
       [ 8.04573391e-03, -3.57392617e-02,  4.93873395e-02,
        -7.19200540e-03,  6.17594225e-04, -9.05684754e-02,
         5.75595237e-02, -4.39445451e-02,  1.74751058e-02,
         5.21203056e-02, -4.62332591e-02,  2.49039251e-02,
         4.80811261e-02,  6.86636344e-02,  3.56147550e-02,
         3.00088692e-02,  2.61450615e-02, -9.05242786e-02,
        -8.02173465e-02,  5.04851453e-02, -7.90870413e-02,
        -1.76850613e-03, -2.48927213e-02,  9.02153179e-02,
         5.83691010e-03, -6.91071302e-02, -6.67965412e-02,
        -6.99115871e-03, -1.04566067e-01, -2.66474020e-02,
         3.05640660e-02,  2.02934332e-02,  2.25454140e-02,
        -4.22680983e-03,  1.11173084e-02,  6.78260401e-02,
         1.06072798e-02,  7.56636113e-02, -8.22777972e-02,
         8.45727697e-03, -6.97611719e-02, -4.21974622e-02,
        -1.05675403e-02,  2.23673210e-02,  5.64497039e-02,
         8.16499349e-03,  1.09344065e-01,  3.16565037e-02,
        -1.76923983e-02, -3.21071222e-02, -3.39976065e-02,
        -4.91865270e-04,  3.72882909e-03,  2.83771995e-02,
        -1.28521733e-02, -1.07931101e-03, -6.32418767e-02,
         6.89901337e-02,  1.77270249e-02, -5.20959273e-02,
         8.28308053e-03,  5.45032136e-02, -5.42099178e-02,
        -4.53332700e-02, -4.07493711e-02, -2.82698255e-02,
         1.23605467e-02, -2.13815887e-02, -2.36266199e-02,
         1.25317844e-02, -2.37170663e-02,  3.97411585e-02,
        -1.24362171e-01,  7.60625675e-02,  5.50833121e-02,
         8.28216895e-02,  2.97119413e-02, -1.84067301e-02,
        -1.96194537e-02,  5.54319024e-02, -3.49143632e-02,
        -4.14677151e-02, -3.37047316e-02,  7.31324553e-02,
         4.41837087e-02,  2.55246125e-02, -8.26404244e-03,
        -1.07323499e-02, -4.26244214e-02, -2.84962379e-03,
         7.38559067e-02,  2.27768477e-02,  7.15384434e-04,
         4.36012223e-02,  5.09080216e-02,  6.38482794e-02,
        -2.73155794e-02, -6.55021593e-02, -7.69265592e-02,
         3.55171375e-02,  9.60494280e-02,  2.18195822e-02,
         1.20155150e-02, -1.17864003e-02, -4.57934802e-03,
        -8.58034287e-03,  3.37150097e-02,  2.31918972e-02,
        -7.58325458e-02, -5.23878746e-02,  4.53933813e-02,
        -3.80786061e-02, -3.34904715e-02,  9.20353234e-02,
         2.87689138e-02, -3.33817266e-02, -1.95853226e-03,
        -3.04530811e-04, -1.70499142e-02,  2.85335910e-02,
        -8.81095454e-02, -4.02252674e-02, -4.00093682e-02,
        -1.03193102e-02, -2.51968428e-02,  2.14092582e-02,
         1.31045297e-01, -5.29633765e-34, -1.09651715e-01,
         1.29811466e-02,  5.92657551e-03,  4.73506488e-02,
        -8.60292558e-03, -3.67089920e-02,  3.05214841e-02,
         5.53067103e-02, -4.71985415e-02, -1.25118876e-02,
        -1.15366466e-01,  9.08006541e-03,  1.07346520e-01,
        -4.94735315e-02, -1.34290727e-02, -4.61562537e-02,
         2.45320462e-02,  9.45082400e-03,  2.04324387e-02,
        -3.99918184e-02, -4.67826389e-02,  2.21171584e-02,
        -4.58187312e-02, -8.13272409e-03, -7.65669812e-03,
         1.92283783e-02,  4.85844538e-02, -2.55902205e-02,
         1.61550229e-03, -1.37180462e-02,  9.67310090e-03,
         7.36411475e-03,  1.14088068e-02,  1.28853470e-01,
         7.71843316e-03,  7.06362203e-02,  2.54451539e-02,
         4.06523868e-02,  2.44038943e-02,  1.43776415e-02,
        -6.00932315e-02,  7.38180652e-02, -2.44701710e-02,
         8.98901671e-02,  3.17052449e-03,  1.01834476e-01,
         4.17741574e-02, -5.95178157e-02, -3.23181450e-02,
         3.80939171e-02,  1.21155838e-02, -4.07834314e-02,
         2.84823179e-02,  4.90988493e-02, -9.35697928e-03,
         6.50074482e-02,  7.23532289e-02, -1.67793036e-02,
        -8.22415575e-03, -1.61573030e-02,  5.96225299e-02,
        -3.36084552e-02,  2.12108232e-02, -6.06090799e-02,
         1.54377624e-01, -7.24146813e-02, -3.77272032e-02,
        -3.26889642e-02, -1.80382060e-03, -1.01960041e-02,
        -1.60677545e-03, -6.91846088e-02,  8.28444511e-02,
         9.88840312e-02,  3.45473574e-03, -9.90247130e-02,
        -3.52827162e-02, -7.13178739e-02, -4.96000946e-02,
        -3.43955085e-02, -8.13041851e-02,  4.81447391e-02,
         5.00679435e-03, -2.21499521e-02, -5.60056865e-02,
         1.00068096e-02, -3.59793454e-02,  1.06184319e-01,
        -4.54196408e-02,  7.16393292e-02, -2.36773510e-02,
         9.98145342e-03,  2.73602046e-02,  1.05985492e-01,
         4.60164249e-02,  9.59029454e-34, -1.12306990e-01,
         2.78911889e-02, -3.35900933e-02,  5.39242700e-02,
        -2.22291313e-02,  1.53769068e-02,  3.10411751e-02,
         3.39010954e-02,  7.43166730e-02,  3.42471153e-02,
        -3.35056870e-03, -2.05350984e-02, -3.62369791e-02,
         2.29334272e-02, -3.01991608e-02, -1.00819945e-01,
         3.29193920e-02,  6.77542612e-02,  1.35644544e-02,
        -5.20550227e-03, -6.58159032e-02,  9.54550803e-02,
        -1.34038934e-02,  1.53885018e-02, -7.22936466e-02,
         9.67836082e-02, -8.08119699e-02, -4.53454675e-03,
        -6.42011315e-02, -4.99278791e-02,  4.64197397e-02,
         2.21340004e-02,  3.13109383e-02,  9.13568512e-02,
        -4.61120494e-02, -1.02761038e-01,  3.04415729e-02,
         5.09875491e-02,  6.70140684e-02,  1.04042431e-02,
         1.63534079e-02,  3.92030627e-02,  2.17153635e-02,
         5.36603332e-02,  3.62809487e-02, -4.22140770e-02,
        -2.47226693e-02,  1.90311708e-02,  3.61724161e-02,
         6.37021735e-02, -3.21582262e-03, -8.50392878e-03,
         3.94655801e-02,  9.02654324e-03,  1.93095654e-02,
         6.60718232e-02,  1.02694873e-02, -4.43854295e-02,
        -1.56523138e-02, -1.55714341e-02,  1.32904621e-02,
        -1.16108647e-02,  4.21831720e-02, -5.44776618e-02,
         1.29237190e-01, -2.25757398e-02,  5.26203550e-02,
        -1.58437118e-02,  9.33164656e-02,  6.38019480e-03,
        -9.36159026e-03, -6.08875342e-02, -3.27308141e-02,
        -3.44816409e-02,  3.29973958e-02, -4.79391888e-02,
        -9.81300771e-02,  2.91164853e-02, -2.70903464e-02,
         1.81866940e-02, -1.73859913e-02, -4.40371186e-02,
        -7.97002465e-02,  3.01646441e-02, -6.35260791e-02,
         1.25962850e-02,  8.50250125e-02, -4.58911099e-02,
         5.81017099e-02, -2.71002855e-02,  8.42775479e-02,
        -4.09972779e-02, -3.37656885e-02,  1.02088815e-02,
        -2.54192557e-02, -1.40610315e-08,  4.94446754e-02,
        -9.04356092e-02, -6.06709905e-02,  8.29530060e-02,
        -3.29032876e-02,  4.14910726e-02,  9.99592431e-03,
         6.96136849e-03,  3.99236800e-03, -3.24333273e-02,
        -3.14657055e-02, -5.33161797e-02, -3.80913094e-02,
         1.62076857e-02,  2.45778989e-02, -7.26419166e-02,
        -6.56893775e-02, -8.23131874e-02, -8.00500810e-02,
        -5.36648929e-02,  5.60894497e-02, -1.10912947e-02,
         9.62166581e-04, -1.22690335e-01, -5.13837114e-02,
         9.96703841e-03,  1.00696050e-02,  1.07073061e-01,
         1.19757699e-02,  1.00423172e-02, -6.28261939e-02,
        -7.49697015e-02, -6.34070160e-03, -2.72201132e-02,
        -1.28096163e-01, -2.62459815e-02, -1.81465298e-02,
        -9.85359699e-02, -3.02990265e-02, -4.02614735e-02,
         9.94290635e-02,  5.35999909e-02,  2.74899639e-02,
        -5.53680072e-03,  8.43570977e-02,  8.35161731e-02,
         3.74304205e-02,  7.11937770e-02,  2.98903026e-02,
         2.32728701e-02, -3.62112634e-02,  6.20540008e-02,
         2.15148628e-02,  5.19732311e-02,  1.45338271e-02,
        -4.60966676e-02,  5.02554402e-02, -7.27027357e-02,
         2.92778611e-02,  5.62662818e-02, -3.86355035e-02,
         1.53832138e-02, -6.23094402e-02, -2.77466550e-02]], dtype=float32)

In [17]:
X = filtered_embeddings
y = df_non_legacy['target_label']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Initialize and train the Logistic Regression model
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)

# Make predictions
y_pred = clf.predict(X_test)

# Generate and print the classification report
report = classification_report(y_test, y_pred)
print(report)

                precision    recall  f1-score   support

Critical Error       0.91      1.00      0.95        48
         Error       0.98      0.89      0.93        47
   HTTP Status       1.00      1.00      1.00       304
Resource Usage       1.00      1.00      1.00        49
Security Alert       1.00      0.99      1.00       123

      accuracy                           0.99       571
     macro avg       0.98      0.98      0.98       571
  weighted avg       0.99      0.99      0.99       571

In [19]:
import joblib

joblib.dump(clf,'../models/log_classifier.joblib')

['../models/log_classifier.joblib']